# Generated by Django 3.1.4 on 2020-12-05 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_dac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edicao',
            name='evento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projeto_dac.evento'),
        ),
    ]
