# Generated by Django 3.1.4 on 2020-12-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_dac', '0002_edicao_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edicao',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='edicao',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
